# Generated by Django 4.0.3 on 2022-06-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apartment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='has_elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
